/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedLogWorkoutRouteImport } from './routes/_authenticated/log.workout'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/_authenticated/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/_authenticated/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLogWorkoutRoute = AuthenticatedLogWorkoutRouteImport.update({
  id: '/_authenticated/log/workout',
  path: '/log/workout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/log/workout': typeof AuthenticatedLogWorkoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/log/workout': typeof AuthenticatedLogWorkoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/log/workout': typeof AuthenticatedLogWorkoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/feed' | '/profile' | '/log/workout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/feed' | '/profile' | '/log/workout'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/_authenticated/feed'
    | '/_authenticated/profile'
    | '/_authenticated/log/workout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedLogWorkoutRoute: typeof AuthenticatedLogWorkoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/log/workout': {
      id: '/_authenticated/log/workout'
      path: '/log/workout'
      fullPath: '/log/workout'
      preLoaderRoute: typeof AuthenticatedLogWorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedLogWorkoutRoute: AuthenticatedLogWorkoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
