/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPtRouteImport } from './routes/_authenticated/pt'
import { Route as AuthenticatedProgressReportRouteImport } from './routes/_authenticated/progress-report'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedInbodyRouteImport } from './routes/_authenticated/inbody'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedLogWorkoutRouteImport } from './routes/_authenticated/log.workout'
import { Route as AuthenticatedLogNutritionReportRouteImport } from './routes/_authenticated/log.nutrition-report'
import { Route as AuthenticatedLogNutritionRouteImport } from './routes/_authenticated/log.nutrition'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPtRoute = AuthenticatedPtRouteImport.update({
  id: '/pt',
  path: '/pt',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgressReportRoute =
  AuthenticatedProgressReportRouteImport.update({
    id: '/progress-report',
    path: '/progress-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInbodyRoute = AuthenticatedInbodyRouteImport.update({
  id: '/inbody',
  path: '/inbody',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogWorkoutRoute = AuthenticatedLogWorkoutRouteImport.update({
  id: '/log/workout',
  path: '/log/workout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogNutritionReportRoute =
  AuthenticatedLogNutritionReportRouteImport.update({
    id: '/log/nutrition-report',
    path: '/log/nutrition-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogNutritionRoute =
  AuthenticatedLogNutritionRouteImport.update({
    id: '/log/nutrition',
    path: '/log/nutrition',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/inbody': typeof AuthenticatedInbodyRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/progress-report': typeof AuthenticatedProgressReportRoute
  '/pt': typeof AuthenticatedPtRoute
  '/log/nutrition': typeof AuthenticatedLogNutritionRoute
  '/log/nutrition-report': typeof AuthenticatedLogNutritionReportRoute
  '/log/workout': typeof AuthenticatedLogWorkoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/inbody': typeof AuthenticatedInbodyRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/progress-report': typeof AuthenticatedProgressReportRoute
  '/pt': typeof AuthenticatedPtRoute
  '/log/nutrition': typeof AuthenticatedLogNutritionRoute
  '/log/nutrition-report': typeof AuthenticatedLogNutritionReportRoute
  '/log/workout': typeof AuthenticatedLogWorkoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/inbody': typeof AuthenticatedInbodyRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/progress-report': typeof AuthenticatedProgressReportRoute
  '/_authenticated/pt': typeof AuthenticatedPtRoute
  '/_authenticated/log/nutrition': typeof AuthenticatedLogNutritionRoute
  '/_authenticated/log/nutrition-report': typeof AuthenticatedLogNutritionReportRoute
  '/_authenticated/log/workout': typeof AuthenticatedLogWorkoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/coach'
    | '/feed'
    | '/inbody'
    | '/plans'
    | '/profile'
    | '/progress'
    | '/progress-report'
    | '/pt'
    | '/log/nutrition'
    | '/log/nutrition-report'
    | '/log/workout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/coach'
    | '/feed'
    | '/inbody'
    | '/plans'
    | '/profile'
    | '/progress'
    | '/progress-report'
    | '/pt'
    | '/log/nutrition'
    | '/log/nutrition-report'
    | '/log/workout'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/coach'
    | '/_authenticated/feed'
    | '/_authenticated/inbody'
    | '/_authenticated/plans'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/progress-report'
    | '/_authenticated/pt'
    | '/_authenticated/log/nutrition'
    | '/_authenticated/log/nutrition-report'
    | '/_authenticated/log/workout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pt': {
      id: '/_authenticated/pt'
      path: '/pt'
      fullPath: '/pt'
      preLoaderRoute: typeof AuthenticatedPtRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progress-report': {
      id: '/_authenticated/progress-report'
      path: '/progress-report'
      fullPath: '/progress-report'
      preLoaderRoute: typeof AuthenticatedProgressReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbody': {
      id: '/_authenticated/inbody'
      path: '/inbody'
      fullPath: '/inbody'
      preLoaderRoute: typeof AuthenticatedInbodyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/log/workout': {
      id: '/_authenticated/log/workout'
      path: '/log/workout'
      fullPath: '/log/workout'
      preLoaderRoute: typeof AuthenticatedLogWorkoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/log/nutrition-report': {
      id: '/_authenticated/log/nutrition-report'
      path: '/log/nutrition-report'
      fullPath: '/log/nutrition-report'
      preLoaderRoute: typeof AuthenticatedLogNutritionReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/log/nutrition': {
      id: '/_authenticated/log/nutrition'
      path: '/log/nutrition'
      fullPath: '/log/nutrition'
      preLoaderRoute: typeof AuthenticatedLogNutritionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedInbodyRoute: typeof AuthenticatedInbodyRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedProgressReportRoute: typeof AuthenticatedProgressReportRoute
  AuthenticatedPtRoute: typeof AuthenticatedPtRoute
  AuthenticatedLogNutritionRoute: typeof AuthenticatedLogNutritionRoute
  AuthenticatedLogNutritionReportRoute: typeof AuthenticatedLogNutritionReportRoute
  AuthenticatedLogWorkoutRoute: typeof AuthenticatedLogWorkoutRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedInbodyRoute: AuthenticatedInbodyRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedProgressReportRoute: AuthenticatedProgressReportRoute,
  AuthenticatedPtRoute: AuthenticatedPtRoute,
  AuthenticatedLogNutritionRoute: AuthenticatedLogNutritionRoute,
  AuthenticatedLogNutritionReportRoute: AuthenticatedLogNutritionReportRoute,
  AuthenticatedLogWorkoutRoute: AuthenticatedLogWorkoutRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
