/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWeeklyAnalysisRouteImport } from './routes/api/weekly-analysis'
import { Route as ApiTodayMotivationRouteImport } from './routes/api/today-motivation'
import { Route as ApiSupportRouteImport } from './routes/api/support'
import { Route as ApiSignupRouteImport } from './routes/api/signup'
import { Route as ApiSignoutRouteImport } from './routes/api/signout'
import { Route as ApiSigninRouteImport } from './routes/api/signin'
import { Route as ApiPtsRouteImport } from './routes/api/pts'
import { Route as ApiPtUnavailabilityBlocksRouteImport } from './routes/api/pt-unavailability-blocks'
import { Route as ApiProgressReportRouteImport } from './routes/api/progress-report'
import { Route as ApiProgressPhotosRouteImport } from './routes/api/progress-photos'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiPlansRouteImport } from './routes/api/plans'
import { Route as ApiPlanFeedbackRouteImport } from './routes/api/plan-feedback'
import { Route as ApiPasswordRouteImport } from './routes/api/password'
import { Route as ApiInbodyRouteImport } from './routes/api/inbody'
import { Route as ApiGuestMeetingsRouteImport } from './routes/api/guest-meetings'
import { Route as ApiGuestMeetingOptionsRouteImport } from './routes/api/guest-meeting-options'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiDebugEchoRouteImport } from './routes/api/debug-echo'
import { Route as ApiCustomersRouteImport } from './routes/api/customers'
import { Route as ApiCurrentUserRouteImport } from './routes/api/current-user'
import { Route as ApiClassesRouteImport } from './routes/api/classes'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiBookingsRouteImport } from './routes/api/bookings'
import { Route as ApiAnalysesRouteImport } from './routes/api/analyses'
import { Route as AuthenticatedTrainerRouteImport } from './routes/_authenticated/trainer'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSiteRouteImport } from './routes/_authenticated/site'
import { Route as AuthenticatedPtInboxRouteImport } from './routes/_authenticated/pt-inbox'
import { Route as AuthenticatedProgressReportRouteImport } from './routes/_authenticated/progress-report'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedPackagesRouteImport } from './routes/_authenticated/packages'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedInbodyRouteImport } from './routes/_authenticated/inbody'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedAnalysesRouteImport } from './routes/_authenticated/analyses'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicPtsRouteImport } from './routes/api/public/pts'
import { Route as ApiPublicPackagesRouteImport } from './routes/api/public/packages'
import { Route as ApiPublicLandingRouteImport } from './routes/api/public/landing'
import { Route as ApiPublicEventsRouteImport } from './routes/api/public/events'
import { Route as ApiPtServicesRouteImport } from './routes/api/pt/services'
import { Route as ApiNutritionAnalyseMealRouteImport } from './routes/api/nutrition.analyse-meal'
import { Route as ApiManagerServicesRouteImport } from './routes/api/manager/services'
import { Route as ApiManagerPurchaseRequestsRouteImport } from './routes/api/manager/purchase-requests'
import { Route as ApiManagerPromotionsRouteImport } from './routes/api/manager/promotions'
import { Route as ApiManagerPaymentsRouteImport } from './routes/api/manager/payments'
import { Route as ApiManagerPackagesRouteImport } from './routes/api/manager/packages'
import { Route as ApiManagerMembershipsRouteImport } from './routes/api/manager/memberships'
import { Route as ApiManagerEventsRouteImport } from './routes/api/manager/events'
import { Route as ApiLogWorkoutRouteImport } from './routes/api/log/workout'
import { Route as ApiLogNutritionReportRouteImport } from './routes/api/log/nutrition-report'
import { Route as ApiInbodyScanRouteImport } from './routes/api/inbody.scan'
import { Route as ApiFeedReportRouteImport } from './routes/api/feed.report'
import { Route as ApiFeedLogMealRouteImport } from './routes/api/feed.log-meal'
import { Route as ApiFeedLikeRouteImport } from './routes/api/feed.like'
import { Route as ApiFeedConfirmMealLogRouteImport } from './routes/api/feed.confirm-meal-log'
import { Route as ApiFeedCommentsRouteImport } from './routes/api/feed.comments'
import { Route as ApiFeedAnalyseMealRouteImport } from './routes/api/feed.analyse-meal'
import { Route as ApiCustomerPackageRequestsRouteImport } from './routes/api/customer/package-requests'
import { Route as ApiCustomerMembershipsRouteImport } from './routes/api/customer/memberships'
import { Route as ApiChatThreadsRouteImport } from './routes/api/chat/threads'
import { Route as ApiChatThreadRouteImport } from './routes/api/chat/thread'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminSiteContentRouteImport } from './routes/api/admin/site-content'
import { Route as ApiAdminPtProfilesRouteImport } from './routes/api/admin/pt-profiles'
import { Route as ApiAdminGymPhotosRouteImport } from './routes/api/admin/gym-photos'
import { Route as AuthenticatedLogWorkoutRouteImport } from './routes/_authenticated/log.workout'
import { Route as AuthenticatedLogNutritionReportRouteImport } from './routes/_authenticated/log.nutrition-report'

const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeeklyAnalysisRoute = ApiWeeklyAnalysisRouteImport.update({
  id: '/api/weekly-analysis',
  path: '/api/weekly-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodayMotivationRoute = ApiTodayMotivationRouteImport.update({
  id: '/api/today-motivation',
  path: '/api/today-motivation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupportRoute = ApiSupportRouteImport.update({
  id: '/api/support',
  path: '/api/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignupRoute = ApiSignupRouteImport.update({
  id: '/api/signup',
  path: '/api/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignoutRoute = ApiSignoutRouteImport.update({
  id: '/api/signout',
  path: '/api/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSigninRoute = ApiSigninRouteImport.update({
  id: '/api/signin',
  path: '/api/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPtsRoute = ApiPtsRouteImport.update({
  id: '/api/pts',
  path: '/api/pts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPtUnavailabilityBlocksRoute =
  ApiPtUnavailabilityBlocksRouteImport.update({
    id: '/api/pt-unavailability-blocks',
    path: '/api/pt-unavailability-blocks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProgressReportRoute = ApiProgressReportRouteImport.update({
  id: '/api/progress-report',
  path: '/api/progress-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressPhotosRoute = ApiProgressPhotosRouteImport.update({
  id: '/api/progress-photos',
  path: '/api/progress-photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansRoute = ApiPlansRouteImport.update({
  id: '/api/plans',
  path: '/api/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanFeedbackRoute = ApiPlanFeedbackRouteImport.update({
  id: '/api/plan-feedback',
  path: '/api/plan-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasswordRoute = ApiPasswordRouteImport.update({
  id: '/api/password',
  path: '/api/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInbodyRoute = ApiInbodyRouteImport.update({
  id: '/api/inbody',
  path: '/api/inbody',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuestMeetingsRoute = ApiGuestMeetingsRouteImport.update({
  id: '/api/guest-meetings',
  path: '/api/guest-meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuestMeetingOptionsRoute = ApiGuestMeetingOptionsRouteImport.update({
  id: '/api/guest-meeting-options',
  path: '/api/guest-meeting-options',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugEchoRoute = ApiDebugEchoRouteImport.update({
  id: '/api/debug-echo',
  path: '/api/debug-echo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomersRoute = ApiCustomersRouteImport.update({
  id: '/api/customers',
  path: '/api/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCurrentUserRoute = ApiCurrentUserRouteImport.update({
  id: '/api/current-user',
  path: '/api/current-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassesRoute = ApiClassesRouteImport.update({
  id: '/api/classes',
  path: '/api/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRoute = ApiBookingsRouteImport.update({
  id: '/api/bookings',
  path: '/api/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalysesRoute = ApiAnalysesRouteImport.update({
  id: '/api/analyses',
  path: '/api/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrainerRoute = AuthenticatedTrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSiteRoute = AuthenticatedSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPtInboxRoute = AuthenticatedPtInboxRouteImport.update({
  id: '/pt-inbox',
  path: '/pt-inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgressReportRoute =
  AuthenticatedProgressReportRouteImport.update({
    id: '/progress-report',
    path: '/progress-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPackagesRoute = AuthenticatedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInbodyRoute = AuthenticatedInbodyRouteImport.update({
  id: '/inbody',
  path: '/inbody',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalysesRoute = AuthenticatedAnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicPtsRoute = ApiPublicPtsRouteImport.update({
  id: '/api/public/pts',
  path: '/api/public/pts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPackagesRoute = ApiPublicPackagesRouteImport.update({
  id: '/api/public/packages',
  path: '/api/public/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLandingRoute = ApiPublicLandingRouteImport.update({
  id: '/api/public/landing',
  path: '/api/public/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventsRoute = ApiPublicEventsRouteImport.update({
  id: '/api/public/events',
  path: '/api/public/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPtServicesRoute = ApiPtServicesRouteImport.update({
  id: '/api/pt/services',
  path: '/api/pt/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNutritionAnalyseMealRoute = ApiNutritionAnalyseMealRouteImport.update({
  id: '/api/nutrition/analyse-meal',
  path: '/api/nutrition/analyse-meal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManagerServicesRoute = ApiManagerServicesRouteImport.update({
  id: '/api/manager/services',
  path: '/api/manager/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManagerPurchaseRequestsRoute =
  ApiManagerPurchaseRequestsRouteImport.update({
    id: '/api/manager/purchase-requests',
    path: '/api/manager/purchase-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiManagerPromotionsRoute = ApiManagerPromotionsRouteImport.update({
  id: '/api/manager/promotions',
  path: '/api/manager/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManagerPaymentsRoute = ApiManagerPaymentsRouteImport.update({
  id: '/api/manager/payments',
  path: '/api/manager/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManagerPackagesRoute = ApiManagerPackagesRouteImport.update({
  id: '/api/manager/packages',
  path: '/api/manager/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManagerMembershipsRoute = ApiManagerMembershipsRouteImport.update({
  id: '/api/manager/memberships',
  path: '/api/manager/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManagerEventsRoute = ApiManagerEventsRouteImport.update({
  id: '/api/manager/events',
  path: '/api/manager/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogWorkoutRoute = ApiLogWorkoutRouteImport.update({
  id: '/api/log/workout',
  path: '/api/log/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogNutritionReportRoute = ApiLogNutritionReportRouteImport.update({
  id: '/api/log/nutrition-report',
  path: '/api/log/nutrition-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInbodyScanRoute = ApiInbodyScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => ApiInbodyRoute,
} as any)
const ApiFeedReportRoute = ApiFeedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => ApiFeedRoute,
} as any)
const ApiFeedLogMealRoute = ApiFeedLogMealRouteImport.update({
  id: '/log-meal',
  path: '/log-meal',
  getParentRoute: () => ApiFeedRoute,
} as any)
const ApiFeedLikeRoute = ApiFeedLikeRouteImport.update({
  id: '/like',
  path: '/like',
  getParentRoute: () => ApiFeedRoute,
} as any)
const ApiFeedConfirmMealLogRoute = ApiFeedConfirmMealLogRouteImport.update({
  id: '/confirm-meal-log',
  path: '/confirm-meal-log',
  getParentRoute: () => ApiFeedRoute,
} as any)
const ApiFeedCommentsRoute = ApiFeedCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => ApiFeedRoute,
} as any)
const ApiFeedAnalyseMealRoute = ApiFeedAnalyseMealRouteImport.update({
  id: '/analyse-meal',
  path: '/analyse-meal',
  getParentRoute: () => ApiFeedRoute,
} as any)
const ApiCustomerPackageRequestsRoute =
  ApiCustomerPackageRequestsRouteImport.update({
    id: '/api/customer/package-requests',
    path: '/api/customer/package-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCustomerMembershipsRoute = ApiCustomerMembershipsRouteImport.update({
  id: '/api/customer/memberships',
  path: '/api/customer/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatThreadsRoute = ApiChatThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatThreadRoute = ApiChatThreadRouteImport.update({
  id: '/thread',
  path: '/thread',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSiteContentRoute = ApiAdminSiteContentRouteImport.update({
  id: '/api/admin/site-content',
  path: '/api/admin/site-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPtProfilesRoute = ApiAdminPtProfilesRouteImport.update({
  id: '/api/admin/pt-profiles',
  path: '/api/admin/pt-profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGymPhotosRoute = ApiAdminGymPhotosRouteImport.update({
  id: '/api/admin/gym-photos',
  path: '/api/admin/gym-photos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLogWorkoutRoute = AuthenticatedLogWorkoutRouteImport.update({
  id: '/log/workout',
  path: '/log/workout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogNutritionReportRoute =
  AuthenticatedLogNutritionReportRouteImport.update({
    id: '/log/nutrition-report',
    path: '/log/nutrition-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/get-started': typeof GetStartedRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/analyses': typeof AuthenticatedAnalysesRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/inbody': typeof AuthenticatedInbodyRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/progress-report': typeof AuthenticatedProgressReportRoute
  '/pt-inbox': typeof AuthenticatedPtInboxRoute
  '/site': typeof AuthenticatedSiteRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/trainer': typeof AuthenticatedTrainerRoute
  '/api/analyses': typeof ApiAnalysesRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/classes': typeof ApiClassesRoute
  '/api/current-user': typeof ApiCurrentUserRoute
  '/api/customers': typeof ApiCustomersRoute
  '/api/debug-echo': typeof ApiDebugEchoRoute
  '/api/feed': typeof ApiFeedRouteWithChildren
  '/api/guest-meeting-options': typeof ApiGuestMeetingOptionsRoute
  '/api/guest-meetings': typeof ApiGuestMeetingsRoute
  '/api/inbody': typeof ApiInbodyRouteWithChildren
  '/api/password': typeof ApiPasswordRoute
  '/api/plan-feedback': typeof ApiPlanFeedbackRoute
  '/api/plans': typeof ApiPlansRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/progress-photos': typeof ApiProgressPhotosRoute
  '/api/progress-report': typeof ApiProgressReportRoute
  '/api/pt-unavailability-blocks': typeof ApiPtUnavailabilityBlocksRoute
  '/api/pts': typeof ApiPtsRoute
  '/api/signin': typeof ApiSigninRoute
  '/api/signout': typeof ApiSignoutRoute
  '/api/signup': typeof ApiSignupRoute
  '/api/support': typeof ApiSupportRoute
  '/api/today-motivation': typeof ApiTodayMotivationRoute
  '/api/weekly-analysis': typeof ApiWeeklyAnalysisRoute
  '/log/nutrition-report': typeof AuthenticatedLogNutritionReportRoute
  '/log/workout': typeof AuthenticatedLogWorkoutRoute
  '/api/admin/gym-photos': typeof ApiAdminGymPhotosRoute
  '/api/admin/pt-profiles': typeof ApiAdminPtProfilesRoute
  '/api/admin/site-content': typeof ApiAdminSiteContentRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/chat/thread': typeof ApiChatThreadRoute
  '/api/chat/threads': typeof ApiChatThreadsRoute
  '/api/customer/memberships': typeof ApiCustomerMembershipsRoute
  '/api/customer/package-requests': typeof ApiCustomerPackageRequestsRoute
  '/api/feed/analyse-meal': typeof ApiFeedAnalyseMealRoute
  '/api/feed/comments': typeof ApiFeedCommentsRoute
  '/api/feed/confirm-meal-log': typeof ApiFeedConfirmMealLogRoute
  '/api/feed/like': typeof ApiFeedLikeRoute
  '/api/feed/log-meal': typeof ApiFeedLogMealRoute
  '/api/feed/report': typeof ApiFeedReportRoute
  '/api/inbody/scan': typeof ApiInbodyScanRoute
  '/api/log/nutrition-report': typeof ApiLogNutritionReportRoute
  '/api/log/workout': typeof ApiLogWorkoutRoute
  '/api/manager/events': typeof ApiManagerEventsRoute
  '/api/manager/memberships': typeof ApiManagerMembershipsRoute
  '/api/manager/packages': typeof ApiManagerPackagesRoute
  '/api/manager/payments': typeof ApiManagerPaymentsRoute
  '/api/manager/promotions': typeof ApiManagerPromotionsRoute
  '/api/manager/purchase-requests': typeof ApiManagerPurchaseRequestsRoute
  '/api/manager/services': typeof ApiManagerServicesRoute
  '/api/nutrition/analyse-meal': typeof ApiNutritionAnalyseMealRoute
  '/api/pt/services': typeof ApiPtServicesRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/landing': typeof ApiPublicLandingRoute
  '/api/public/packages': typeof ApiPublicPackagesRoute
  '/api/public/pts': typeof ApiPublicPtsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/get-started': typeof GetStartedRoute
  '/analyses': typeof AuthenticatedAnalysesRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/inbody': typeof AuthenticatedInbodyRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/progress-report': typeof AuthenticatedProgressReportRoute
  '/pt-inbox': typeof AuthenticatedPtInboxRoute
  '/site': typeof AuthenticatedSiteRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/trainer': typeof AuthenticatedTrainerRoute
  '/api/analyses': typeof ApiAnalysesRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/classes': typeof ApiClassesRoute
  '/api/current-user': typeof ApiCurrentUserRoute
  '/api/customers': typeof ApiCustomersRoute
  '/api/debug-echo': typeof ApiDebugEchoRoute
  '/api/feed': typeof ApiFeedRouteWithChildren
  '/api/guest-meeting-options': typeof ApiGuestMeetingOptionsRoute
  '/api/guest-meetings': typeof ApiGuestMeetingsRoute
  '/api/inbody': typeof ApiInbodyRouteWithChildren
  '/api/password': typeof ApiPasswordRoute
  '/api/plan-feedback': typeof ApiPlanFeedbackRoute
  '/api/plans': typeof ApiPlansRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/progress-photos': typeof ApiProgressPhotosRoute
  '/api/progress-report': typeof ApiProgressReportRoute
  '/api/pt-unavailability-blocks': typeof ApiPtUnavailabilityBlocksRoute
  '/api/pts': typeof ApiPtsRoute
  '/api/signin': typeof ApiSigninRoute
  '/api/signout': typeof ApiSignoutRoute
  '/api/signup': typeof ApiSignupRoute
  '/api/support': typeof ApiSupportRoute
  '/api/today-motivation': typeof ApiTodayMotivationRoute
  '/api/weekly-analysis': typeof ApiWeeklyAnalysisRoute
  '/log/nutrition-report': typeof AuthenticatedLogNutritionReportRoute
  '/log/workout': typeof AuthenticatedLogWorkoutRoute
  '/api/admin/gym-photos': typeof ApiAdminGymPhotosRoute
  '/api/admin/pt-profiles': typeof ApiAdminPtProfilesRoute
  '/api/admin/site-content': typeof ApiAdminSiteContentRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/chat/thread': typeof ApiChatThreadRoute
  '/api/chat/threads': typeof ApiChatThreadsRoute
  '/api/customer/memberships': typeof ApiCustomerMembershipsRoute
  '/api/customer/package-requests': typeof ApiCustomerPackageRequestsRoute
  '/api/feed/analyse-meal': typeof ApiFeedAnalyseMealRoute
  '/api/feed/comments': typeof ApiFeedCommentsRoute
  '/api/feed/confirm-meal-log': typeof ApiFeedConfirmMealLogRoute
  '/api/feed/like': typeof ApiFeedLikeRoute
  '/api/feed/log-meal': typeof ApiFeedLogMealRoute
  '/api/feed/report': typeof ApiFeedReportRoute
  '/api/inbody/scan': typeof ApiInbodyScanRoute
  '/api/log/nutrition-report': typeof ApiLogNutritionReportRoute
  '/api/log/workout': typeof ApiLogWorkoutRoute
  '/api/manager/events': typeof ApiManagerEventsRoute
  '/api/manager/memberships': typeof ApiManagerMembershipsRoute
  '/api/manager/packages': typeof ApiManagerPackagesRoute
  '/api/manager/payments': typeof ApiManagerPaymentsRoute
  '/api/manager/promotions': typeof ApiManagerPromotionsRoute
  '/api/manager/purchase-requests': typeof ApiManagerPurchaseRequestsRoute
  '/api/manager/services': typeof ApiManagerServicesRoute
  '/api/nutrition/analyse-meal': typeof ApiNutritionAnalyseMealRoute
  '/api/pt/services': typeof ApiPtServicesRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/landing': typeof ApiPublicLandingRoute
  '/api/public/packages': typeof ApiPublicPackagesRoute
  '/api/public/pts': typeof ApiPublicPtsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/get-started': typeof GetStartedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/analyses': typeof AuthenticatedAnalysesRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/inbody': typeof AuthenticatedInbodyRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/packages': typeof AuthenticatedPackagesRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/progress-report': typeof AuthenticatedProgressReportRoute
  '/_authenticated/pt-inbox': typeof AuthenticatedPtInboxRoute
  '/_authenticated/site': typeof AuthenticatedSiteRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/trainer': typeof AuthenticatedTrainerRoute
  '/api/analyses': typeof ApiAnalysesRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/classes': typeof ApiClassesRoute
  '/api/current-user': typeof ApiCurrentUserRoute
  '/api/customers': typeof ApiCustomersRoute
  '/api/debug-echo': typeof ApiDebugEchoRoute
  '/api/feed': typeof ApiFeedRouteWithChildren
  '/api/guest-meeting-options': typeof ApiGuestMeetingOptionsRoute
  '/api/guest-meetings': typeof ApiGuestMeetingsRoute
  '/api/inbody': typeof ApiInbodyRouteWithChildren
  '/api/password': typeof ApiPasswordRoute
  '/api/plan-feedback': typeof ApiPlanFeedbackRoute
  '/api/plans': typeof ApiPlansRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/progress-photos': typeof ApiProgressPhotosRoute
  '/api/progress-report': typeof ApiProgressReportRoute
  '/api/pt-unavailability-blocks': typeof ApiPtUnavailabilityBlocksRoute
  '/api/pts': typeof ApiPtsRoute
  '/api/signin': typeof ApiSigninRoute
  '/api/signout': typeof ApiSignoutRoute
  '/api/signup': typeof ApiSignupRoute
  '/api/support': typeof ApiSupportRoute
  '/api/today-motivation': typeof ApiTodayMotivationRoute
  '/api/weekly-analysis': typeof ApiWeeklyAnalysisRoute
  '/_authenticated/log/nutrition-report': typeof AuthenticatedLogNutritionReportRoute
  '/_authenticated/log/workout': typeof AuthenticatedLogWorkoutRoute
  '/api/admin/gym-photos': typeof ApiAdminGymPhotosRoute
  '/api/admin/pt-profiles': typeof ApiAdminPtProfilesRoute
  '/api/admin/site-content': typeof ApiAdminSiteContentRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/chat/thread': typeof ApiChatThreadRoute
  '/api/chat/threads': typeof ApiChatThreadsRoute
  '/api/customer/memberships': typeof ApiCustomerMembershipsRoute
  '/api/customer/package-requests': typeof ApiCustomerPackageRequestsRoute
  '/api/feed/analyse-meal': typeof ApiFeedAnalyseMealRoute
  '/api/feed/comments': typeof ApiFeedCommentsRoute
  '/api/feed/confirm-meal-log': typeof ApiFeedConfirmMealLogRoute
  '/api/feed/like': typeof ApiFeedLikeRoute
  '/api/feed/log-meal': typeof ApiFeedLogMealRoute
  '/api/feed/report': typeof ApiFeedReportRoute
  '/api/inbody/scan': typeof ApiInbodyScanRoute
  '/api/log/nutrition-report': typeof ApiLogNutritionReportRoute
  '/api/log/workout': typeof ApiLogWorkoutRoute
  '/api/manager/events': typeof ApiManagerEventsRoute
  '/api/manager/memberships': typeof ApiManagerMembershipsRoute
  '/api/manager/packages': typeof ApiManagerPackagesRoute
  '/api/manager/payments': typeof ApiManagerPaymentsRoute
  '/api/manager/promotions': typeof ApiManagerPromotionsRoute
  '/api/manager/purchase-requests': typeof ApiManagerPurchaseRequestsRoute
  '/api/manager/services': typeof ApiManagerServicesRoute
  '/api/nutrition/analyse-meal': typeof ApiNutritionAnalyseMealRoute
  '/api/pt/services': typeof ApiPtServicesRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/landing': typeof ApiPublicLandingRoute
  '/api/public/packages': typeof ApiPublicPackagesRoute
  '/api/public/pts': typeof ApiPublicPtsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/get-started'
    | '/admin'
    | '/analyses'
    | '/bookings'
    | '/change-password'
    | '/classes'
    | '/feed'
    | '/inbody'
    | '/nutrition'
    | '/packages'
    | '/plans'
    | '/profile'
    | '/progress'
    | '/progress-report'
    | '/pt-inbox'
    | '/site'
    | '/staff'
    | '/trainer'
    | '/api/analyses'
    | '/api/bookings'
    | '/api/chat'
    | '/api/classes'
    | '/api/current-user'
    | '/api/customers'
    | '/api/debug-echo'
    | '/api/feed'
    | '/api/guest-meeting-options'
    | '/api/guest-meetings'
    | '/api/inbody'
    | '/api/password'
    | '/api/plan-feedback'
    | '/api/plans'
    | '/api/profile'
    | '/api/progress-photos'
    | '/api/progress-report'
    | '/api/pt-unavailability-blocks'
    | '/api/pts'
    | '/api/signin'
    | '/api/signout'
    | '/api/signup'
    | '/api/support'
    | '/api/today-motivation'
    | '/api/weekly-analysis'
    | '/log/nutrition-report'
    | '/log/workout'
    | '/api/admin/gym-photos'
    | '/api/admin/pt-profiles'
    | '/api/admin/site-content'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/chat/thread'
    | '/api/chat/threads'
    | '/api/customer/memberships'
    | '/api/customer/package-requests'
    | '/api/feed/analyse-meal'
    | '/api/feed/comments'
    | '/api/feed/confirm-meal-log'
    | '/api/feed/like'
    | '/api/feed/log-meal'
    | '/api/feed/report'
    | '/api/inbody/scan'
    | '/api/log/nutrition-report'
    | '/api/log/workout'
    | '/api/manager/events'
    | '/api/manager/memberships'
    | '/api/manager/packages'
    | '/api/manager/payments'
    | '/api/manager/promotions'
    | '/api/manager/purchase-requests'
    | '/api/manager/services'
    | '/api/nutrition/analyse-meal'
    | '/api/pt/services'
    | '/api/public/events'
    | '/api/public/landing'
    | '/api/public/packages'
    | '/api/public/pts'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/get-started'
    | '/analyses'
    | '/bookings'
    | '/change-password'
    | '/classes'
    | '/feed'
    | '/inbody'
    | '/nutrition'
    | '/packages'
    | '/plans'
    | '/profile'
    | '/progress'
    | '/progress-report'
    | '/pt-inbox'
    | '/site'
    | '/staff'
    | '/trainer'
    | '/api/analyses'
    | '/api/bookings'
    | '/api/chat'
    | '/api/classes'
    | '/api/current-user'
    | '/api/customers'
    | '/api/debug-echo'
    | '/api/feed'
    | '/api/guest-meeting-options'
    | '/api/guest-meetings'
    | '/api/inbody'
    | '/api/password'
    | '/api/plan-feedback'
    | '/api/plans'
    | '/api/profile'
    | '/api/progress-photos'
    | '/api/progress-report'
    | '/api/pt-unavailability-blocks'
    | '/api/pts'
    | '/api/signin'
    | '/api/signout'
    | '/api/signup'
    | '/api/support'
    | '/api/today-motivation'
    | '/api/weekly-analysis'
    | '/log/nutrition-report'
    | '/log/workout'
    | '/api/admin/gym-photos'
    | '/api/admin/pt-profiles'
    | '/api/admin/site-content'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/chat/thread'
    | '/api/chat/threads'
    | '/api/customer/memberships'
    | '/api/customer/package-requests'
    | '/api/feed/analyse-meal'
    | '/api/feed/comments'
    | '/api/feed/confirm-meal-log'
    | '/api/feed/like'
    | '/api/feed/log-meal'
    | '/api/feed/report'
    | '/api/inbody/scan'
    | '/api/log/nutrition-report'
    | '/api/log/workout'
    | '/api/manager/events'
    | '/api/manager/memberships'
    | '/api/manager/packages'
    | '/api/manager/payments'
    | '/api/manager/promotions'
    | '/api/manager/purchase-requests'
    | '/api/manager/services'
    | '/api/nutrition/analyse-meal'
    | '/api/pt/services'
    | '/api/public/events'
    | '/api/public/landing'
    | '/api/public/packages'
    | '/api/public/pts'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/get-started'
    | '/_authenticated/admin'
    | '/_authenticated/analyses'
    | '/_authenticated/bookings'
    | '/_authenticated/change-password'
    | '/_authenticated/classes'
    | '/_authenticated/feed'
    | '/_authenticated/inbody'
    | '/_authenticated/nutrition'
    | '/_authenticated/packages'
    | '/_authenticated/plans'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/progress-report'
    | '/_authenticated/pt-inbox'
    | '/_authenticated/site'
    | '/_authenticated/staff'
    | '/_authenticated/trainer'
    | '/api/analyses'
    | '/api/bookings'
    | '/api/chat'
    | '/api/classes'
    | '/api/current-user'
    | '/api/customers'
    | '/api/debug-echo'
    | '/api/feed'
    | '/api/guest-meeting-options'
    | '/api/guest-meetings'
    | '/api/inbody'
    | '/api/password'
    | '/api/plan-feedback'
    | '/api/plans'
    | '/api/profile'
    | '/api/progress-photos'
    | '/api/progress-report'
    | '/api/pt-unavailability-blocks'
    | '/api/pts'
    | '/api/signin'
    | '/api/signout'
    | '/api/signup'
    | '/api/support'
    | '/api/today-motivation'
    | '/api/weekly-analysis'
    | '/_authenticated/log/nutrition-report'
    | '/_authenticated/log/workout'
    | '/api/admin/gym-photos'
    | '/api/admin/pt-profiles'
    | '/api/admin/site-content'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/chat/thread'
    | '/api/chat/threads'
    | '/api/customer/memberships'
    | '/api/customer/package-requests'
    | '/api/feed/analyse-meal'
    | '/api/feed/comments'
    | '/api/feed/confirm-meal-log'
    | '/api/feed/like'
    | '/api/feed/log-meal'
    | '/api/feed/report'
    | '/api/inbody/scan'
    | '/api/log/nutrition-report'
    | '/api/log/workout'
    | '/api/manager/events'
    | '/api/manager/memberships'
    | '/api/manager/packages'
    | '/api/manager/payments'
    | '/api/manager/promotions'
    | '/api/manager/purchase-requests'
    | '/api/manager/services'
    | '/api/nutrition/analyse-meal'
    | '/api/pt/services'
    | '/api/public/events'
    | '/api/public/landing'
    | '/api/public/packages'
    | '/api/public/pts'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  GetStartedRoute: typeof GetStartedRoute
  ApiAnalysesRoute: typeof ApiAnalysesRoute
  ApiBookingsRoute: typeof ApiBookingsRoute
  ApiChatRoute: typeof ApiChatRouteWithChildren
  ApiClassesRoute: typeof ApiClassesRoute
  ApiCurrentUserRoute: typeof ApiCurrentUserRoute
  ApiCustomersRoute: typeof ApiCustomersRoute
  ApiDebugEchoRoute: typeof ApiDebugEchoRoute
  ApiFeedRoute: typeof ApiFeedRouteWithChildren
  ApiGuestMeetingOptionsRoute: typeof ApiGuestMeetingOptionsRoute
  ApiGuestMeetingsRoute: typeof ApiGuestMeetingsRoute
  ApiInbodyRoute: typeof ApiInbodyRouteWithChildren
  ApiPasswordRoute: typeof ApiPasswordRoute
  ApiPlanFeedbackRoute: typeof ApiPlanFeedbackRoute
  ApiPlansRoute: typeof ApiPlansRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiProgressPhotosRoute: typeof ApiProgressPhotosRoute
  ApiProgressReportRoute: typeof ApiProgressReportRoute
  ApiPtUnavailabilityBlocksRoute: typeof ApiPtUnavailabilityBlocksRoute
  ApiPtsRoute: typeof ApiPtsRoute
  ApiSigninRoute: typeof ApiSigninRoute
  ApiSignoutRoute: typeof ApiSignoutRoute
  ApiSignupRoute: typeof ApiSignupRoute
  ApiSupportRoute: typeof ApiSupportRoute
  ApiTodayMotivationRoute: typeof ApiTodayMotivationRoute
  ApiWeeklyAnalysisRoute: typeof ApiWeeklyAnalysisRoute
  ApiAdminGymPhotosRoute: typeof ApiAdminGymPhotosRoute
  ApiAdminPtProfilesRoute: typeof ApiAdminPtProfilesRoute
  ApiAdminSiteContentRoute: typeof ApiAdminSiteContentRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiCustomerMembershipsRoute: typeof ApiCustomerMembershipsRoute
  ApiCustomerPackageRequestsRoute: typeof ApiCustomerPackageRequestsRoute
  ApiLogNutritionReportRoute: typeof ApiLogNutritionReportRoute
  ApiLogWorkoutRoute: typeof ApiLogWorkoutRoute
  ApiManagerEventsRoute: typeof ApiManagerEventsRoute
  ApiManagerMembershipsRoute: typeof ApiManagerMembershipsRoute
  ApiManagerPackagesRoute: typeof ApiManagerPackagesRoute
  ApiManagerPaymentsRoute: typeof ApiManagerPaymentsRoute
  ApiManagerPromotionsRoute: typeof ApiManagerPromotionsRoute
  ApiManagerPurchaseRequestsRoute: typeof ApiManagerPurchaseRequestsRoute
  ApiManagerServicesRoute: typeof ApiManagerServicesRoute
  ApiNutritionAnalyseMealRoute: typeof ApiNutritionAnalyseMealRoute
  ApiPtServicesRoute: typeof ApiPtServicesRoute
  ApiPublicEventsRoute: typeof ApiPublicEventsRoute
  ApiPublicLandingRoute: typeof ApiPublicLandingRoute
  ApiPublicPackagesRoute: typeof ApiPublicPackagesRoute
  ApiPublicPtsRoute: typeof ApiPublicPtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weekly-analysis': {
      id: '/api/weekly-analysis'
      path: '/api/weekly-analysis'
      fullPath: '/api/weekly-analysis'
      preLoaderRoute: typeof ApiWeeklyAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/today-motivation': {
      id: '/api/today-motivation'
      path: '/api/today-motivation'
      fullPath: '/api/today-motivation'
      preLoaderRoute: typeof ApiTodayMotivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/support': {
      id: '/api/support'
      path: '/api/support'
      fullPath: '/api/support'
      preLoaderRoute: typeof ApiSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signup': {
      id: '/api/signup'
      path: '/api/signup'
      fullPath: '/api/signup'
      preLoaderRoute: typeof ApiSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signout': {
      id: '/api/signout'
      path: '/api/signout'
      fullPath: '/api/signout'
      preLoaderRoute: typeof ApiSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signin': {
      id: '/api/signin'
      path: '/api/signin'
      fullPath: '/api/signin'
      preLoaderRoute: typeof ApiSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pts': {
      id: '/api/pts'
      path: '/api/pts'
      fullPath: '/api/pts'
      preLoaderRoute: typeof ApiPtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pt-unavailability-blocks': {
      id: '/api/pt-unavailability-blocks'
      path: '/api/pt-unavailability-blocks'
      fullPath: '/api/pt-unavailability-blocks'
      preLoaderRoute: typeof ApiPtUnavailabilityBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress-report': {
      id: '/api/progress-report'
      path: '/api/progress-report'
      fullPath: '/api/progress-report'
      preLoaderRoute: typeof ApiProgressReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress-photos': {
      id: '/api/progress-photos'
      path: '/api/progress-photos'
      fullPath: '/api/progress-photos'
      preLoaderRoute: typeof ApiProgressPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans': {
      id: '/api/plans'
      path: '/api/plans'
      fullPath: '/api/plans'
      preLoaderRoute: typeof ApiPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan-feedback': {
      id: '/api/plan-feedback'
      path: '/api/plan-feedback'
      fullPath: '/api/plan-feedback'
      preLoaderRoute: typeof ApiPlanFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/password': {
      id: '/api/password'
      path: '/api/password'
      fullPath: '/api/password'
      preLoaderRoute: typeof ApiPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbody': {
      id: '/api/inbody'
      path: '/api/inbody'
      fullPath: '/api/inbody'
      preLoaderRoute: typeof ApiInbodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guest-meetings': {
      id: '/api/guest-meetings'
      path: '/api/guest-meetings'
      fullPath: '/api/guest-meetings'
      preLoaderRoute: typeof ApiGuestMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guest-meeting-options': {
      id: '/api/guest-meeting-options'
      path: '/api/guest-meeting-options'
      fullPath: '/api/guest-meeting-options'
      preLoaderRoute: typeof ApiGuestMeetingOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-echo': {
      id: '/api/debug-echo'
      path: '/api/debug-echo'
      fullPath: '/api/debug-echo'
      preLoaderRoute: typeof ApiDebugEchoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customers': {
      id: '/api/customers'
      path: '/api/customers'
      fullPath: '/api/customers'
      preLoaderRoute: typeof ApiCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/current-user': {
      id: '/api/current-user'
      path: '/api/current-user'
      fullPath: '/api/current-user'
      preLoaderRoute: typeof ApiCurrentUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classes': {
      id: '/api/classes'
      path: '/api/classes'
      fullPath: '/api/classes'
      preLoaderRoute: typeof ApiClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings': {
      id: '/api/bookings'
      path: '/api/bookings'
      fullPath: '/api/bookings'
      preLoaderRoute: typeof ApiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyses': {
      id: '/api/analyses'
      path: '/api/analyses'
      fullPath: '/api/analyses'
      preLoaderRoute: typeof ApiAnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trainer': {
      id: '/_authenticated/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof AuthenticatedTrainerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/site': {
      id: '/_authenticated/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof AuthenticatedSiteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pt-inbox': {
      id: '/_authenticated/pt-inbox'
      path: '/pt-inbox'
      fullPath: '/pt-inbox'
      preLoaderRoute: typeof AuthenticatedPtInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progress-report': {
      id: '/_authenticated/progress-report'
      path: '/progress-report'
      fullPath: '/progress-report'
      preLoaderRoute: typeof AuthenticatedProgressReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/packages': {
      id: '/_authenticated/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedPackagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbody': {
      id: '/_authenticated/inbody'
      path: '/inbody'
      fullPath: '/inbody'
      preLoaderRoute: typeof AuthenticatedInbodyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyses': {
      id: '/_authenticated/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AuthenticatedAnalysesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/pts': {
      id: '/api/public/pts'
      path: '/api/public/pts'
      fullPath: '/api/public/pts'
      preLoaderRoute: typeof ApiPublicPtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/packages': {
      id: '/api/public/packages'
      path: '/api/public/packages'
      fullPath: '/api/public/packages'
      preLoaderRoute: typeof ApiPublicPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/landing': {
      id: '/api/public/landing'
      path: '/api/public/landing'
      fullPath: '/api/public/landing'
      preLoaderRoute: typeof ApiPublicLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/events': {
      id: '/api/public/events'
      path: '/api/public/events'
      fullPath: '/api/public/events'
      preLoaderRoute: typeof ApiPublicEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pt/services': {
      id: '/api/pt/services'
      path: '/api/pt/services'
      fullPath: '/api/pt/services'
      preLoaderRoute: typeof ApiPtServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nutrition/analyse-meal': {
      id: '/api/nutrition/analyse-meal'
      path: '/api/nutrition/analyse-meal'
      fullPath: '/api/nutrition/analyse-meal'
      preLoaderRoute: typeof ApiNutritionAnalyseMealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manager/services': {
      id: '/api/manager/services'
      path: '/api/manager/services'
      fullPath: '/api/manager/services'
      preLoaderRoute: typeof ApiManagerServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manager/purchase-requests': {
      id: '/api/manager/purchase-requests'
      path: '/api/manager/purchase-requests'
      fullPath: '/api/manager/purchase-requests'
      preLoaderRoute: typeof ApiManagerPurchaseRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manager/promotions': {
      id: '/api/manager/promotions'
      path: '/api/manager/promotions'
      fullPath: '/api/manager/promotions'
      preLoaderRoute: typeof ApiManagerPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manager/payments': {
      id: '/api/manager/payments'
      path: '/api/manager/payments'
      fullPath: '/api/manager/payments'
      preLoaderRoute: typeof ApiManagerPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manager/packages': {
      id: '/api/manager/packages'
      path: '/api/manager/packages'
      fullPath: '/api/manager/packages'
      preLoaderRoute: typeof ApiManagerPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manager/memberships': {
      id: '/api/manager/memberships'
      path: '/api/manager/memberships'
      fullPath: '/api/manager/memberships'
      preLoaderRoute: typeof ApiManagerMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manager/events': {
      id: '/api/manager/events'
      path: '/api/manager/events'
      fullPath: '/api/manager/events'
      preLoaderRoute: typeof ApiManagerEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/log/workout': {
      id: '/api/log/workout'
      path: '/api/log/workout'
      fullPath: '/api/log/workout'
      preLoaderRoute: typeof ApiLogWorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/log/nutrition-report': {
      id: '/api/log/nutrition-report'
      path: '/api/log/nutrition-report'
      fullPath: '/api/log/nutrition-report'
      preLoaderRoute: typeof ApiLogNutritionReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbody/scan': {
      id: '/api/inbody/scan'
      path: '/scan'
      fullPath: '/api/inbody/scan'
      preLoaderRoute: typeof ApiInbodyScanRouteImport
      parentRoute: typeof ApiInbodyRoute
    }
    '/api/feed/report': {
      id: '/api/feed/report'
      path: '/report'
      fullPath: '/api/feed/report'
      preLoaderRoute: typeof ApiFeedReportRouteImport
      parentRoute: typeof ApiFeedRoute
    }
    '/api/feed/log-meal': {
      id: '/api/feed/log-meal'
      path: '/log-meal'
      fullPath: '/api/feed/log-meal'
      preLoaderRoute: typeof ApiFeedLogMealRouteImport
      parentRoute: typeof ApiFeedRoute
    }
    '/api/feed/like': {
      id: '/api/feed/like'
      path: '/like'
      fullPath: '/api/feed/like'
      preLoaderRoute: typeof ApiFeedLikeRouteImport
      parentRoute: typeof ApiFeedRoute
    }
    '/api/feed/confirm-meal-log': {
      id: '/api/feed/confirm-meal-log'
      path: '/confirm-meal-log'
      fullPath: '/api/feed/confirm-meal-log'
      preLoaderRoute: typeof ApiFeedConfirmMealLogRouteImport
      parentRoute: typeof ApiFeedRoute
    }
    '/api/feed/comments': {
      id: '/api/feed/comments'
      path: '/comments'
      fullPath: '/api/feed/comments'
      preLoaderRoute: typeof ApiFeedCommentsRouteImport
      parentRoute: typeof ApiFeedRoute
    }
    '/api/feed/analyse-meal': {
      id: '/api/feed/analyse-meal'
      path: '/analyse-meal'
      fullPath: '/api/feed/analyse-meal'
      preLoaderRoute: typeof ApiFeedAnalyseMealRouteImport
      parentRoute: typeof ApiFeedRoute
    }
    '/api/customer/package-requests': {
      id: '/api/customer/package-requests'
      path: '/api/customer/package-requests'
      fullPath: '/api/customer/package-requests'
      preLoaderRoute: typeof ApiCustomerPackageRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer/memberships': {
      id: '/api/customer/memberships'
      path: '/api/customer/memberships'
      fullPath: '/api/customer/memberships'
      preLoaderRoute: typeof ApiCustomerMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/threads': {
      id: '/api/chat/threads'
      path: '/threads'
      fullPath: '/api/chat/threads'
      preLoaderRoute: typeof ApiChatThreadsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/thread': {
      id: '/api/chat/thread'
      path: '/thread'
      fullPath: '/api/chat/thread'
      preLoaderRoute: typeof ApiChatThreadRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/site-content': {
      id: '/api/admin/site-content'
      path: '/api/admin/site-content'
      fullPath: '/api/admin/site-content'
      preLoaderRoute: typeof ApiAdminSiteContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/pt-profiles': {
      id: '/api/admin/pt-profiles'
      path: '/api/admin/pt-profiles'
      fullPath: '/api/admin/pt-profiles'
      preLoaderRoute: typeof ApiAdminPtProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/gym-photos': {
      id: '/api/admin/gym-photos'
      path: '/api/admin/gym-photos'
      fullPath: '/api/admin/gym-photos'
      preLoaderRoute: typeof ApiAdminGymPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/log/workout': {
      id: '/_authenticated/log/workout'
      path: '/log/workout'
      fullPath: '/log/workout'
      preLoaderRoute: typeof AuthenticatedLogWorkoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/log/nutrition-report': {
      id: '/_authenticated/log/nutrition-report'
      path: '/log/nutrition-report'
      fullPath: '/log/nutrition-report'
      preLoaderRoute: typeof AuthenticatedLogNutritionReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAnalysesRoute: typeof AuthenticatedAnalysesRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedInbodyRoute: typeof AuthenticatedInbodyRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedPackagesRoute: typeof AuthenticatedPackagesRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedProgressReportRoute: typeof AuthenticatedProgressReportRoute
  AuthenticatedPtInboxRoute: typeof AuthenticatedPtInboxRoute
  AuthenticatedSiteRoute: typeof AuthenticatedSiteRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedTrainerRoute: typeof AuthenticatedTrainerRoute
  AuthenticatedLogNutritionReportRoute: typeof AuthenticatedLogNutritionReportRoute
  AuthenticatedLogWorkoutRoute: typeof AuthenticatedLogWorkoutRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAnalysesRoute: AuthenticatedAnalysesRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedInbodyRoute: AuthenticatedInbodyRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedPackagesRoute: AuthenticatedPackagesRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedProgressReportRoute: AuthenticatedProgressReportRoute,
  AuthenticatedPtInboxRoute: AuthenticatedPtInboxRoute,
  AuthenticatedSiteRoute: AuthenticatedSiteRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedTrainerRoute: AuthenticatedTrainerRoute,
  AuthenticatedLogNutritionReportRoute: AuthenticatedLogNutritionReportRoute,
  AuthenticatedLogWorkoutRoute: AuthenticatedLogWorkoutRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiChatRouteChildren {
  ApiChatThreadRoute: typeof ApiChatThreadRoute
  ApiChatThreadsRoute: typeof ApiChatThreadsRoute
}

const ApiChatRouteChildren: ApiChatRouteChildren = {
  ApiChatThreadRoute: ApiChatThreadRoute,
  ApiChatThreadsRoute: ApiChatThreadsRoute,
}

const ApiChatRouteWithChildren =
  ApiChatRoute._addFileChildren(ApiChatRouteChildren)

interface ApiFeedRouteChildren {
  ApiFeedAnalyseMealRoute: typeof ApiFeedAnalyseMealRoute
  ApiFeedCommentsRoute: typeof ApiFeedCommentsRoute
  ApiFeedConfirmMealLogRoute: typeof ApiFeedConfirmMealLogRoute
  ApiFeedLikeRoute: typeof ApiFeedLikeRoute
  ApiFeedLogMealRoute: typeof ApiFeedLogMealRoute
  ApiFeedReportRoute: typeof ApiFeedReportRoute
}

const ApiFeedRouteChildren: ApiFeedRouteChildren = {
  ApiFeedAnalyseMealRoute: ApiFeedAnalyseMealRoute,
  ApiFeedCommentsRoute: ApiFeedCommentsRoute,
  ApiFeedConfirmMealLogRoute: ApiFeedConfirmMealLogRoute,
  ApiFeedLikeRoute: ApiFeedLikeRoute,
  ApiFeedLogMealRoute: ApiFeedLogMealRoute,
  ApiFeedReportRoute: ApiFeedReportRoute,
}

const ApiFeedRouteWithChildren =
  ApiFeedRoute._addFileChildren(ApiFeedRouteChildren)

interface ApiInbodyRouteChildren {
  ApiInbodyScanRoute: typeof ApiInbodyScanRoute
}

const ApiInbodyRouteChildren: ApiInbodyRouteChildren = {
  ApiInbodyScanRoute: ApiInbodyScanRoute,
}

const ApiInbodyRouteWithChildren = ApiInbodyRoute._addFileChildren(
  ApiInbodyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  GetStartedRoute: GetStartedRoute,
  ApiAnalysesRoute: ApiAnalysesRoute,
  ApiBookingsRoute: ApiBookingsRoute,
  ApiChatRoute: ApiChatRouteWithChildren,
  ApiClassesRoute: ApiClassesRoute,
  ApiCurrentUserRoute: ApiCurrentUserRoute,
  ApiCustomersRoute: ApiCustomersRoute,
  ApiDebugEchoRoute: ApiDebugEchoRoute,
  ApiFeedRoute: ApiFeedRouteWithChildren,
  ApiGuestMeetingOptionsRoute: ApiGuestMeetingOptionsRoute,
  ApiGuestMeetingsRoute: ApiGuestMeetingsRoute,
  ApiInbodyRoute: ApiInbodyRouteWithChildren,
  ApiPasswordRoute: ApiPasswordRoute,
  ApiPlanFeedbackRoute: ApiPlanFeedbackRoute,
  ApiPlansRoute: ApiPlansRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiProgressPhotosRoute: ApiProgressPhotosRoute,
  ApiProgressReportRoute: ApiProgressReportRoute,
  ApiPtUnavailabilityBlocksRoute: ApiPtUnavailabilityBlocksRoute,
  ApiPtsRoute: ApiPtsRoute,
  ApiSigninRoute: ApiSigninRoute,
  ApiSignoutRoute: ApiSignoutRoute,
  ApiSignupRoute: ApiSignupRoute,
  ApiSupportRoute: ApiSupportRoute,
  ApiTodayMotivationRoute: ApiTodayMotivationRoute,
  ApiWeeklyAnalysisRoute: ApiWeeklyAnalysisRoute,
  ApiAdminGymPhotosRoute: ApiAdminGymPhotosRoute,
  ApiAdminPtProfilesRoute: ApiAdminPtProfilesRoute,
  ApiAdminSiteContentRoute: ApiAdminSiteContentRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiCustomerMembershipsRoute: ApiCustomerMembershipsRoute,
  ApiCustomerPackageRequestsRoute: ApiCustomerPackageRequestsRoute,
  ApiLogNutritionReportRoute: ApiLogNutritionReportRoute,
  ApiLogWorkoutRoute: ApiLogWorkoutRoute,
  ApiManagerEventsRoute: ApiManagerEventsRoute,
  ApiManagerMembershipsRoute: ApiManagerMembershipsRoute,
  ApiManagerPackagesRoute: ApiManagerPackagesRoute,
  ApiManagerPaymentsRoute: ApiManagerPaymentsRoute,
  ApiManagerPromotionsRoute: ApiManagerPromotionsRoute,
  ApiManagerPurchaseRequestsRoute: ApiManagerPurchaseRequestsRoute,
  ApiManagerServicesRoute: ApiManagerServicesRoute,
  ApiNutritionAnalyseMealRoute: ApiNutritionAnalyseMealRoute,
  ApiPtServicesRoute: ApiPtServicesRoute,
  ApiPublicEventsRoute: ApiPublicEventsRoute,
  ApiPublicLandingRoute: ApiPublicLandingRoute,
  ApiPublicPackagesRoute: ApiPublicPackagesRoute,
  ApiPublicPtsRoute: ApiPublicPtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
